### ISSUE TITLE
WebGL contexts virtualization

### ISSUE THREAD

**Issue by chrisplatorres** [exokitxr/exokit-web#18]
Got the following error after opening 15+ reality tab sites simultaneously. Which resulted in a "crashed" canvas.

> Graphics.js:121 WARNING: Too many active WebGL contexts. Oldest context will be lost.

![toomanyCapture](https://user-images.githubusercontent.com/29695350/64296123-d169c980-cf38-11e9-92ed-66cebc8212ab.PNG)

**Comment by chrisplatorres** [comment]
Got similar error on Firefox:
> Error: WebGL warning: <SetDimensions>: Exceeded 16 live WebGL contexts for this principal, losing the least recently used one.

**Comment by chrisplatorres** [comment]
related: https://bugs.chromium.org/p/chromium/issues/detail?id=226868

**Comment by modulesio** [comment]
Surprisingly we can fix this. Our contexts are already virtualized so getting around this would mostly just cost performance.

**Comment by modulesio** [comment]
I'll take a crack at this, since it should significantly improve the engine and the demo page.

- Should fix this issue (too many GL contexts)
- Should fix clear jank: https://github.com/exokitxr/exokit-web/issues/6
- Should remove need for `xrCompatible` hacks on GL context creation,, which is currently a bit of a pain and divergence from how Chrome behaves; many sites do not follow spec and recover from context loss

**Comment by modulesio** [comment]
Although https://github.com/exokitxr/exokit-web/issues/24 fixed the macOS error, we still get render sometimes not happening.

I think that's due to the context sharing/loss, which moves this issue to a release blocker.
