### ISSUE TITLE
Transform gizmo on demo site

### ISSUE THREAD

**Issue by modulesio** [exokitxr/exokit-web#9]
We should put reality tab transform gizmos up on the demo site, to show that reality tabs can be moved separate from the camera.

**Comment by chrisplatorres** [comment]
the issue is the pointer `x` , `y` is not logging correctly:

`pointer = {"x":null,"y":null,"button":0}`

the pointer calculation is based on the mouse x,y in relation to the element's bounding rectangle, which is logging all 0 values:

`renderer.domElement rec = {"x":0,"y":0,"width":0,"height":0,"top":0,"right":0,"bottom":0,"left":0}`

 from `renderer.domElement.getBoundingClientRect()`

**Comment by modulesio** [comment]
We'll need to translate the coordinates from the top-level canvas to the internal ones.

**Comment by modulesio** [comment]
This is deployed, but still broken due to an alignment issue (https://github.com/exokitxr/exokit-web/issues/33).

Closing in favor of that one.
